# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(related_name='joined_user', to='travelbuddy.User'),
        ),
    ]
