# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_trip_joined_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(related_name='joined_trips', to='travelbuddy.User'),
        ),
    ]
